apiVersion: v1
kind: Pod
metadata:
  name: polls
  labels:
    function: webserver
spec:
  containers:
  - name: polls
    image: ghcr.io/gavinwy/cis92-01:milestone-5.1
    livenessProbe:
      httpGet:
        path: /polls/
        port: 80
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 80
    env:
    - name: SECRET_KEY
      value: "blahblah"
    - name: PORT
      value: "80"
    - name: DB_NAME
      value: "mysite"
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "django"
    - name: DB_HOST
      value: "postgres.default.svc.cluster.local"